version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - config/docker.env

  database:
    image: postgres:11.5
    env_file:
      - config/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  db_data:
