version: '3'

services:
  web:
    build: .
    entrypoint: /usr/src/app/docker-entrypoint.sh
    command: ["rails", "s", "-b", "0.0.0.0"]
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - config/docker.env
    depends_on:
      - database
      - redis
      - sidekiq
    tty: true
    stdin_open: true

  vue:
    build: ./vue
    ports:
      - '8080:8080'
    volumes:
      - ./vue:/usr/src/app
    depends_on:
      - web

  database:
    image: postgres:11.5
    env_file:
      - config/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0

  sidekiq:
    build: .
    volumes:
      - .:/usr/src/app
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - config/docker.env

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'
      - '1025:1025'

  middleman:
    build: documentation/.
    volumes:
      - .:/usr/src/app
    env_file:
      - config/docker.env
    ports:
      - '4567:4567'

volumes:
  db_data:
